name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '42 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'IGNORED ISSUE'
        stale-pr-message: 'IGNORED PR'
        stale-issue-label: 'no-activity'
        stale-pr-label: 'no-pr-activity'
